'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LIBRARY_SYSTEM_IN_FISHER_VALLEY_COLLEGE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _44962126_12DE_42C7_BCAE_ABB537026728_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{44962126-12DE-42C7-BCAE-ABB537026728}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _44962126_12DE_42C7_BCAE_ABB537026728_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{44962126-12DE-42C7-BCAE-ABB537026728}1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4EBBE486_D879_4CF0_AA27_34B66C33211E_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{4EBBE486-D879-4CF0-AA27-34B66C33211E}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4EBBE486_D879_4CF0_AA27_34B66C33211E_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{4EBBE486-D879-4CF0-AA27-34B66C33211E}1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6589236C_6109_4AC6_887B_9AC040F661B7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{6589236C-6109-4AC6-887B-9AC040F661B7}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _A0DF6743_89CC_4595_A3E3_7962AA7C6ABC_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{A0DF6743-89CC-4595-A3E3-7962AA7C6ABC}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _B6325D80_0E9D_46BB_9B7C_027AB01B1AEE_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{B6325D80-0E9D-46BB-9B7C-027AB01B1AEE}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _EEAD098F_FC14_4E53_8380_06DE4A851199_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{EEAD098F-FC14-4E53-8380-06DE4A851199}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _F05D3536_EF6F_453B_A65C_746E448B028D_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("{F05D3536-EF6F-453B-A65C-746E448B028D}", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
